project:
  type: website
  output-dir: .

website:
  title: "Diversity in Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Cpril
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

